### ISSUE TITLE
Schema version not being set properly

### ISSUE THREAD

**Issue by TheAngryByrd** [vytautask/Hangfire.PostgreSql#1]
I'm getting an error occasionally:
```
 Error while executing install/upgrade [] cont...
Npgsql.NpgsqlException (0x80004005): 42701: column "updatecount" of relation "counter" already exists
   at Npgsql.NpgsqlConnector.DoReadSingleMessage(DataRowLoadingMode dataRowLoadingMode, Boolean returnNullForAsyncMessage, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadSingleMessage(DataRowLoadingMode dataRowLoadingMode, Boolean returnNullForAsyncMessage)
   at Npgsql.NpgsqlConnector.SkipUntil(BackendMessageCode stopAt1, BackendMessageCode stopAt2)
   at Npgsql.NpgsqlDataReader.SkipUntil(BackendMessageCode stopAt1, BackendMessageCode stopAt2)
   at Npgsql.NpgsqlDataReader.NextResultInternal()
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlDataReader.Init()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteNonQueryInternal()
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)
```

Seems like the schema version is still at 3 and not being updated.

**Comment by vytautask** [comment]
Can not reproduce the issue... 
Will look into that later today.

**Comment by TheAngryByrd** [comment]
I'll see if I can put together a sample app, but like most things, it probably only happens on non samples =\

**Comment by vytautask** [comment]
Hm... All tests pass successfully despite my schema deletion or whatever...
Maybe it has something to do with database permissions for hangfire user you are using?

**Comment by vytautask** [comment]
Does this continue to be an issue? 
I'll close the issue if not...

**Comment by TheAngryByrd** [comment]
Go ahead and close it.  Thanks :)
