### ISSUE TITLE
Worker execution error?

### ISSUE THREAD

**Issue by towts** [vytautask/Hangfire.PostgreSql#3]
anyone see this before? this is spammig my error logs.

```
Error occurred during execution of 'Worker #07db7556' process. Execution will be retried (attempt 3 of 2147483647) in 00:00:08 seconds. 
Npgsql.PostgresException (0x80004005): 40001: could not serialize access due to concurrent update
   at Npgsql.NpgsqlConnector.DoReadMessage(DataRowLoadingMode dataRowLoadingMode, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessageWithPrepended(DataRowLoadingMode dataRowLoadingMode)
   at Npgsql.NpgsqlDataReader.NextResultInternal()
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderInternal(CommandBehavior behavior)
   at Dapper.SqlMapper.<QueryImpl>d__61`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Hangfire.PostgreSql.PostgreSqlJobQueue.<>c__DisplayClass4_0.<Dequeue_Transaction>b__0()
   at Hangfire.PostgreSql.Utils.TryExecute[T](Func`1 func, T& result, Func`2 smoothExValidator, Nullable`1 tryCount)
   at Hangfire.PostgreSql.PostgreSqlJobQueue.Dequeue_Transaction(String[] queues, CancellationToken cancellationToken)
   at Hangfire.PostgreSql.PostgreSqlJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.PostgreSql.PostgreSqlConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
```

**Comment by vytautask** [comment]
Strange...
How many workers are you running? Is there a possibility that the same job was being updated while some worker/server tried to execute it?
Maybe you could provide some code/more info about this issue??

**Comment by towts** [comment]
right, well service that is using hangfire is running on three servers, so there are three instances of hangfire running. they all use the same DB. they each use 20 workers.


"prod-api-n2:5904:ed4ddec8-4e10-4bf5-9273-d96ed8996069";"{"WorkerCount":20,"Queues":["default"],"StartedAt":"2016-07-27T13:12:27.7926465Z"}";"2016-07-27 19:47:05.304304"

"prod-api-n3:5220:8afb1a73-ab5d-49cd-8a2b-e257a74bc791";"{"WorkerCount":20,"Queues":["default"],"StartedAt":"2016-07-27T13:14:12.9132781Z"}";"2016-07-27 19:47:05.304537"

"prod-api-n1:4800:634204e6-9acf-4f0c-b911-3d961a43095c";"{"WorkerCount":20,"Queues":["default"],"StartedAt":"2016-07-27T13:12:35.1752583Z"}";"2016-07-27 19:47:05.312146"

**Comment by vytautask** [comment]
What version of PostgreSql are you using? Any chance it could be 9,3?
I am thinking about this thing: https://www.postgresql.org/message-id/20151014164844.3019.25750@wrigleys.postgresql.org ...

**Comment by towts** [comment]
currently at 9.4.5

**Comment by vytautask** [comment]
Managed to test myself. Issue gone. Closing issue.
@towts: thank you for informing me about your problem! ;)

**Comment by towts** [comment]
thanks for looking into it. i will check it out!
